language: go

go:
  - 1.7.x
  - 1.8.x

os:
 - linux
 - osx

install:
 - go get github.com/rakyll/statik
 - go generate
 - go get -t -v ./...

script:
 - go install 
 - go install ./...
 - go test -v -race ./...
